package postgresql

import (
	"context"
	"time"

	"github.com/cmlabs-hris/hris-backend-go/internal/domain/auth"
	"github.com/cmlabs-hris/hris-backend-go/internal/pkg/database"
	"github.com/jackc/pgx/v5"
)

type PasswordResetRepository interface {
	CreatePasswordResetToken(ctx context.Context, userID string, expiresAt time.Time, ipAddress string) (token string, err error)
	GetPasswordResetToken(ctx context.Context, token string) (userID string, expiresAt time.Time, usedAt *time.Time, err error)
	MarkPasswordResetTokenUsed(ctx context.Context, token string) error
	InvalidateAllUserTokens(ctx context.Context, userID string) error
}

type passwordResetRepositoryImpl struct {
	db *database.DB
}

// NewPasswordResetRepository creates a new instance of PasswordResetRepository.
func NewPasswordResetRepository(db *database.DB) PasswordResetRepository {
	return &passwordResetRepositoryImpl{db: db}
}

// CreatePasswordResetToken creates a new password reset token for a user.
// Token is generated by database using UUIDv7.
func (r *passwordResetRepositoryImpl) CreatePasswordResetToken(ctx context.Context, userID string, expiresAt time.Time, ipAddress string) (string, error) {
	q := GetQuerier(ctx, r.db)
	query := `
		INSERT INTO password_reset_tokens (user_id, expires_at, ip_address)
		VALUES ($1, $2, $3)
		RETURNING token
	`
	var token string
	err := q.QueryRow(ctx, query, userID, expiresAt, ipAddress).Scan(&token)
	if err != nil {
		return "", err
	}
	return token, nil
}

// GetPasswordResetToken retrieves a password reset token's details.
func (r *passwordResetRepositoryImpl) GetPasswordResetToken(ctx context.Context, token string) (string, time.Time, *time.Time, error) {
	q := GetQuerier(ctx, r.db)

	query := `
		SELECT user_id, expires_at, used_at
		FROM password_reset_tokens
		WHERE token = $1
	`

	var userID string
	var expiresAt time.Time
	var usedAt *time.Time

	err := q.QueryRow(ctx, query, token).Scan(&userID, &expiresAt, &usedAt)
	if err != nil {
		if err == pgx.ErrNoRows {
			return "", time.Time{}, nil, auth.ErrPasswordResetTokenNotFound
		}
		return "", time.Time{}, nil, err
	}

	return userID, expiresAt, usedAt, nil
}

// MarkPasswordResetTokenUsed marks a password reset token as used.
func (r *passwordResetRepositoryImpl) MarkPasswordResetTokenUsed(ctx context.Context, token string) error {
	q := GetQuerier(ctx, r.db)

	query := `
		UPDATE password_reset_tokens
		SET used_at = NOW()
		WHERE token = $1 AND used_at IS NULL
	`
	_, err := q.Exec(ctx, query, token)
	return err
}

// InvalidateAllUserTokens invalidates all password reset tokens for a user.
func (r *passwordResetRepositoryImpl) InvalidateAllUserTokens(ctx context.Context, userID string) error {
	q := GetQuerier(ctx, r.db)

	query := `
		UPDATE password_reset_tokens
		SET used_at = NOW()
		WHERE user_id = $1 AND used_at IS NULL
	`
	_, err := q.Exec(ctx, query, userID)
	return err
}
